### ISSUE TITLE
Intermittent "connection reset by peer" errors

### ISSUE THREAD

**Issue by adamstrawson** [GoogleCloudPlatform/alloydb-auth-proxy#514] opened 2023-11-29 12:07 UTC
### Bug Description

We're experiencing intermittent disconnects when connecting to AlloyDB, the disconnects appear to be coming specifically from the GCP auth proxy on the GCP side

The issue only occurs when connecting via the Auth Proxy ports `5433` - Connecting directly to AlloyDB on `5432` behaves normally. 

The behaviour and errors are the same as what we previously had with CloudSQL (which @enocom assisted with) - https://github.com/GoogleCloudPlatform/cloud-sql-proxy/issues/1717

```
{"severity":"ERROR","timestamp":"2023-11-29T09:43:17.915Z","message":"[<snip>] failed to connect to instance: Dial error: handshake failed (instance URI = \"<snip>\"): read tcp <snip>:45548-><snip>:5433: read: connection reset by peer\n"}
{"severity":"ERROR","timestamp":"2023-11-29T09:43:22.452Z","message":"[Health Check] Readiness failed: Dial error: handshake failed (instance URI = \"<snip>\"): read tcp <snip>:45568-><snip>:5433: read: connection reset by peer"}
{"severity":"ERROR","timestamp":"2023-11-29T09:43:22.919Z","message":"[<snip>] failed to connect to instance: Dial error: handshake failed (instance URI = \"<snip>\"): read tcp <snip>:45576-><snip>:5433: read: connection reset by peer\n"}
{"severity":"ERROR","timestamp":"2023-11-29T09:43:47.766Z","message":"[<snip>] failed to connect to instance: Dial error: handshake failed (instance URI = \"<snip>\"): read tcp <snip>:45330-><snip>:5433: read: connection reset by peer\n"
```

We have a support case open (48257350), but sharing here as I know @enocom has some context already when helping resolve this within CloudSQL. 

For context, the cause previously was that the Auth Proxy node within GCP was OOM'ing 

### Steps to reproduce?

N/A

### Environment

1. OS type and version: GKE
2. AlloyDB Proxy version: `1.5.0`

**Comment by jackwotherspoon** [comment] 2023-11-29 15:18
Assigning this over to @enocom as it seems he has background knowledge already

**Comment by enocom** [comment] 2023-11-29 16:47
Thanks for the report @adamstrawson. Let me reach out to the backend team to see if we can move this along.

**Comment by enocom** [comment] 2023-11-29 17:16
Out of curiosity, does your connection pool handle these disconnects well? In other words, does the failure last for long enough to affect your app?

**Comment by adamstrawson** [comment] 2023-11-29 18:33
> Out of curiosity, does your connection pool handle these disconnects well? In other words, does the failure last for long enough to affect your app?

Nope, we get a high number of exception alerts due to the connection failures when it occurs.  Mostly `SQLTransientConnectionException` or `PoolInitializationException`

**Comment by enocom** [comment] 2023-12-04 18:00
We've found what we think the root cause of this in the backend code and are working on a fix. Given the release freezes coming up this month, the timing isn't great and will probably take awhile to ship the fix. I'll update here with more details when we have them.

As a workaround, you can use Auto IAM AuthN with a direct connection:

- [database/sql](https://github.com/GoogleCloudPlatform/alloydb-go-connector/blob/main/direct_pgxpool_test.go)
- [pgxpool](https://github.com/GoogleCloudPlatform/alloydb-go-connector/blob/main/direct_pgxpool_test.go)

**Comment by adamstrawson** [comment] 2023-12-05 09:43
Thanks @enocom, had an email from Sam on this too this morning. 

To avoid any engineering effort, I assume this is only affecting the AlloyDB Auth Proxy (within GCP, not this sidecar container proxy) when using IAM? If we drop our users to use the `built-in` types, then we'll avoid this bug in the mean time while we wait for a fix?

**Comment by enocom** [comment] 2023-12-05 20:24
Sorry for the slow response. Yes, you're correct. This bug affects Auto IAM AuthN only. So you'll have to fall back to v1.4.1. Once we fix this, you'll be able to connect without these errors on v1.5.0.

**Comment by phoenix2x** [comment] 2023-12-18 20:59
Hi guys,

We see a similar issue when using [alloydb-go-connector v1.5.0](https://github.com/GoogleCloudPlatform/alloydb-go-connector) with IAM auth.

Intermittent errors like this:
Dial error: failed to dial (instance URI = "xxxx"): dial tcp xxxx:5433: connect: connection refused
Dial error: handshake failed (instance URI = "xxx"): read tcp xxxx:36640-xxxx:5433: read: connection reset by peer

Since we also get "connection refused" I'm not 100% sure it's the same issue, but wanted to post here first before creating a separate one.

Is there an ETA for the fix?

Thank you.

**Comment by enocom** [comment] 2023-12-18 22:49
Thanks @phoenix2x. Yes, that looks like that the same error.

ETA is ASAP, but we're in the middle of a release freeze, so probably sometime in January. We have a fix ready and now just need to roll it out.

**Comment by Tony4469** [comment] 2024-01-08 09:00
Hi @enocom 
Do you know if the deployment freeze is over? We're also blocked by this issue, we can't use alloydb in prod yet

**Comment by adamstrawson** [comment] 2024-01-08 14:09
> Hi @enocom Do you know if the deployment freeze is over? We're also blocked by this issue, we can't use alloydb in prod yet

I don't work for GCP, but we've had the patch applied to our cluster, however there's still an issue that we're experiencing which is being investigated at the moment.

**Comment by enocom** [comment] 2024-01-08 16:14
The rollout should be in progress. I'll update here (and close this issue) when it's done.

**Comment by Tony4469** [comment] 2024-01-22 08:42
Hi @enocom , sorry to spam you again. Any update on the rollout?
Only point remaining for us to use alloy in prod, we can't wait 🤗

**Comment by jamesmancz** [comment] 2024-02-01 16:13
@enocom How's the fix rollout for this issue going?  We're about ready to move some heavy traffic from BigQuery to AlloyDB and this is the only blocker at the moment.

**Comment by enocom** [comment] 2024-02-01 17:58
Rollout has started. I'm just as eager to get this fixed and close this thread. I'll update here (or close) as soon as we have any news.

**Closed** 2024-02-26 16:13 UTC
Labels: type: bug, priority: p2
